### ISSUE TITLE
Many functions require numpy after 1.6

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#365]
#355 uses `numpy.matmul` which was added in 1.10 (in my defense, that information was _buried_.) So that means 0.2.2 will essentially require 1.10 unless I cut that functionality out. It's probably work-around-able but not much fun. I'd like to avoid doing a subminor release that bumps dependency requirements, so I'll make a workaround...I don't care if it's slow and cruddy, it's a workaround.

See also #362.

**Comment by balarsen** [comment]
TO be fair 1.10 came out May 29, 2016, so I am not that hard up on 4 year old releases.

**Comment by jtniehof** [comment]
But wait, it's worse! And most of this is my fault. Testing on 1.6:

poppy.boots_ci: uses numpy.stack, 1.10
datamanager.rebin: digitize fails on some input ("object too deep"), not clear what version of numpy the issue is
datamanager.rebin: uses numpy.matmul, requires 1.10
datamanager.insert_fill: raises "array cannot be safely cast to required type", version requirement unclear
pycdf type conversion raises "Cannot convert generic objects to CDF type."
toolbox.quaternionNormalize: now uses "axis" argument on numpy.norm, requires 1.8
pybats.bats treetrace: raises "list object has no attribute size"
pybats.IMF input: raises "total size of new array must be unchanged"
pycdf.istp.VarBundle: raises 'NotImplementedType' object has no attribute 'ravel', also lots of "object of too small depth for desired array"
pycdf.istp.VarBundle: lots of use of isclose, requires 1.7.0
toolbox.normalize fails when using NaN, version not clear.

I Introduced the "stack" requirement for poppy in 0.2.1. so we've already had one release that requires numpy 1.10 without documenting it. The options are to try and unpickle all this so that 0.2.2 meets our promise of working on 1.6, or just bumping the requirement to 1.10 on 0.2.2 with mea culpa that this actually happened earlier. I honestly prefer door number 2...nobody's complained about 0.2.1 on 1.6, so why waste the effort? @drsteve , @spacecataz , thoughts?

I've also been planning on setting up a better release notes thing which can include the dependency version requirements for each release (starting with 0.2.2 forward, not going to try and reconstruct this backwad.)

**Comment by jtniehof** [comment]
treetrace (test test_pybats.TestBats2d.testPlotting) still fails on 1.10, but that's a single thing, so I'm hoping it's addressable and we can use 1.10 as the requirement. Checking on other dependencies now....

**Comment by balarsen** [comment]
It may be worth a quick look at our other major dependencies. What numpy
does scipy or matplptlib require. No need for heroics if the dependencies
bumped for us.

**Comment by jtniehof** [comment]
poisson_fit requires scipy 0.11.0, and our stated requirement is 0.10.0. This goes back to release 0.2.0. matplotlib 1.5 still looks good, at least.

@balarsen : as far as other deps go, it depends on their versions. Yes SciPy 1.5 requires numpy 1.14, but we don't require SciPy 1.5.

**Comment by jtniehof** [comment]
Rest of our deps:
dateutil: 1.4 suffices, couldn't test earlier (nothing earlier available in pip)
ffnet: we knew 0.7 works, confirmed, 0.6 isn't available in pip so not really worth testing with.
h5py: 2.6 works; I can't get a working install of 2.5 so couldn't test with that
matplotlib: 1.5 still works
networkx: 1.0 works, didn't test with earlier

**Comment by jtniehof** [comment]
I got treetrace to work with numpy 1.10.4, scipy 0.11.0, Python 2.7.18. It might have been failing because of older scipy or something, but I'm going to consider that good and if I run into issues in setting up the test environments for #366, I'll address it there. Going to just make sure all the requirements above are captured and stick a fork in this one.
